USE MAHESH;
---comprison op---
CREATE TABLE EMPLOYEE(ID INT,NAME VARCHAR(20),SALARY INT);
INSERT INTO EMPLOYEE (ID,NAME,SALARY) VALUES (1,"SAI",10000),(2,"NANI",15000),(3,"GOPI",20000),(4,"RAVI",25000);
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE SALARY=10000;
SELECT * FROM EMPLOYEE WHERE SALARY!=5000;
SELECT * FROM EMPLOYEE WHERE SALARY>20000;
SELECT * FROM EMPLOYEE WHERE SALARY<15000;
SELECT * FROM EMPLOYEE WHERE SALARY<=10000;
SELECT * FROM EMPLOYEE WHERE SALARY>=20000;
----logical op----
SELECT * FROM EMPLOYEE WHERE SALARY=10000 AND NAME="SAI";
SELECT * FROM EMPLOYEE WHERE SALARY=20000 OR NAME="SAI";
SELECT * FROM EMPLOYEE WHERE NOT SALARY=15000;
-------------------
ALTER TABLE EMPLOYEE ADD COLUMN AGE INT;
SET SQL_SAFE_UPDATES=0;
UPDATE EMPLOYEE SET AGE=22 WHERE SALARY;
-----null op---
SELECT * FROM EMPLOYEE WHERE AGE IS NULL;
SELECT * FROM EMPLOYEE WHERE AGE IS NOT NULL;
----between op---
SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 15000 AND 25000;
----- in op----
SELECT * FROM EMPLOYEE WHERE SALARY IN(15000,25000);
---case op----
SELECT *,
CASE
	WHEN SALARY>20000 THEN "2X"
    WHEN SALARY>15000 THEN"1X"
ELSE 0
END AS BONUS
FROM EMPLOYEE;
