USE MAHESH;
CREATE TABlE EMP1(ID INT,NAME VARCHAR(50),city varchar(20));

INSERT INTO EMP1(ID,NAME,CITY) VALUES (1,"SAI","AMERICA"),(2,"VARDHAN","INDIA"),(3,"MAHESH","NEW YORK"),(4,"NANI","LONDON");

SELECT * FROM EMP1;

SELECT CONCAT("SAI"," ","VARDHAN") AS FULLNAME;

SELECT CONCAT_WS(" "," ","SAI","VARDHAN") AS NAMES;

SELECT LOWER("HELLO") AS CAPITAL;
SELECT UPPER("HELLO") AS LOWER;
SELECT NAME,UPPER ("MAHESH") AS CAPITAL,CITY,LOWER("NEW YORK") AS SMALL FROM EMP1;

SELECT ID,LENGTH("RAVI") AS NAMELENGTH,CHAR_LENGTH("RAVI") AS NAMECHAR_LENGTH FROM EMP1;

SELECT SUBSTRING("MAHESH",2,4) AS SUBSTRING;

SELECT NAME,REVERSE ("VARDHAN") AS REVERSE FROM EMP1;

SELECT REPLACE("MAHESH","H","V") AS REPLACE_STRING;

SELECT "MAHESH" LIKE "%NA" AS XYZ;
SELECT ID,NAME FROM EMP1 WHERE CITY LIKE "LOND_N";
